---
name: Lint
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  markdown:
    name: markdown
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint
        uses: actionshub/markdownlint@main
  dockerfile:
    name: dockerfile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          trusted-registries: docker.io,ghcr.io
  shell-scripts:
    name: shell scripts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          scandir: ./scripts ./context/etc/features.d ./context/usr/bin
  yaml:
    name: yaml
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Yamllint
        uses: frenck/action-yamllint@v1.3.1
