name: Lint
on: pull_request

jobs:
  markdownlint:
    name: markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run markdownlint
      uses: actionshub/markdownlint@2.0.2
    - name: Run hadolint
      uses: hadolint/hadolint-action@v3.0.0
      with:
        trusted-registries: docker.io,ghcr.io
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        scandir: ./context/etc/features.d ./context/usr/bin
