---
name: Docker build
on: push

jobs:
  php-versions:
    name: Lookup PHP versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.php_versions }}
    steps:
      - uses: actions/checkout@v3
      - name: Lookup PHP versions
        run: echo "php_versions=$(make _versions)" >> $GITHUB_ENV
  build:
    name: PHP
    runs-on: ubuntu-latest
    needs: php-versions
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJSON(needs.php-versions.outputs.matrix) }}
        platform: [linux/arm64, linux/amd64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build PHP ${{ matrix.php }} (${{ matrix.platform }})
        uses: docker/build-push-action@v3
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        with:
          file: "Dockerfile"
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          context: .
          platforms: ${{ matrix.platform }}
          build-args: "php=${{ matrix.php }}"
          labels: |
            org.opencontainers.image.title=PHP ${{ matrix.php }}
            org.opencontainers.image.description=Docker image for PHP ${{ matrix.php }} FPM
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ matrix.php }}-${{ github.sha }}
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.php }}
          load: ${{ (matrix.platform == 'linux/amd64') && (github.ref != format('refs/heads/{0}', github.event.repository.default_branch)) }}
      - uses: e1himself/goss-installation-action@v1.1.0
        if: ${{ (matrix.platform == 'linux/amd64') && (github.ref != format('refs/heads/{0}', github.event.repository.default_branch)) }}
      - name: Test PHP ${{ matrix.php }}
        if: ${{ (matrix.platform == 'linux/amd64') && (github.ref != format('refs/heads/{0}', github.event.repository.default_branch)) }}
        run: |
          # Sleep a bit to ensure that PHP-FPM has time to start up.
          GOSS_SLEEP=15 dgoss run -e PHP_VERSION="${{ matrix.php }}" ghcr.io/${{ github.repository }}:${{ matrix.php }}
