---
name: Release
on:
  workflow_run:
    workflows: ["Docker build"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  php-versions:
    name: Lookup PHP versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.php_versions }}
    steps:
      - uses: actions/checkout@v3
      - name: Lookup PHP versions
        run: echo "php_versions=$(make _versions)" >> $GITHUB_ENV
  build:
    name: PHP
    runs-on: ubuntu-latest
    needs: php-versions
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJSON(needs.php-versions.outputs.matrix) }}
        platform: [linux/arm64, linux/amd64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
      - name: Build PHP ${{ matrix.php }} (${{ matrix.platform }})
        uses: docker/build-push-action@v3
        with:
          file: "Dockerfile"
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          context: .
          platforms: ${{ matrix.platform }}
          build-args: "php=${{ matrix.php }}"
          labels: |
            org.opencontainers.image.title=PHP ${{ matrix.php }}
            org.opencontainers.image.description=Docker image for PHP ${{ matrix.php }} FPM
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ matrix.php }}-${{ github.sha }}
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.php }}
