---
name: Update PHP Docker images

on:
  workflow_dispatch:
  schedule:
    - cron: "00 6 * * *"

permissions:
  contents: read

jobs:
  php-update:
    name: Update PHP Docker image SHAs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: "Run update script"
        run: ./scripts/update.sh
      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: Dockerfile
          commit-message: Update PHP Docker image SHAs
          branch: update-php-docker-image-shas
          delete-branch: true
          title: Update PHP Docker image SHAs
          token: ${{ secrets.PAT_TOKEN }}
